### ISSUE TITLE
Crear el dashboard

### ISSUE THREAD

**Issue by David-Lazaro-Fernandez** [David-Lazaro-Fernandez/Shamir_Oneal#8]
### Description 🗒
Crear un dashboard y enrutarlo para el usuario

### Screenshots 📸
![image](https://user-images.githubusercontent.com/57787993/207936905-68f26cae-51d2-4a6d-8271-44715b26b11f.png)

### Tasks 🔨
Asegurate de completar las siguientes tareas 
- [ ] Crear un nav con las páginas a las que puede ir el usuario
- [ ] Crear un botón para salir de la sesión
- [ ] Crear diferentes componentes para mostrar graficas
- [ ] Asegurarse de que sea reactiva la página  

Remember to use helpful labels and milestones.

**Comment by David-Lazaro-Fernandez** [comment]
@CesarAHO123 @LaloCode 
Les dejo asignada esta tarea para ustedes :) 
Cualquier cosa que necesiten o tengan dudas sientanse libre de preguntarme. 
> Por el momento no tenemos el contexto suficiente como para saber de donde vamos a sacar la información de las graficas por lo que por el momento pueden hardcodear todo 🤭
